import Head from 'next/head'
import LandingPage from '../components/LandingPage'

export default function Home() {
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Snapsync</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <LandingPage />
    </div>
  )
}
